# -------------------------------------------------------------------------------------------------
# git plugin options and fixes

# Make git file completion faster.
# http://talkings.org/post/5236392664/zsh-and-slow-git-completion
__git_files () {
    _wanted files expl 'local files' _files
}

# Fixes a problem with hat notation in git from zsh, e.g. git reset HEAD^
# This passes the bad match onto the command.
# http://github.com/robbyrussell/oh-my-zsh/issues/449
unsetopt nomatch

# -------------------------------------------------------------------------------------------------
# Load env variables and shell config.

setopt sh_word_split
source "$HOME/.profile"
source "$HOME/dotfiles/scripts/load_shell_config"
unsetopt sh_word_split
